### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Junyu-Z** [UkcheolShin/ThermalMonoDepth#2]
in common/data_prepare/prepare_train_data_VIVID.py
![2022-07-24 16-17-55 的屏幕截图](https://user-images.githubusercontent.com/99400116/180638578-0aae8eb7-e521-41b4-9180-547f4ddb5bd2.png)

For 'indoor_robust_varying_well_lit' sequence, why 'RGB' folder contents and 'Thermal' folder contents are exchanged? Is this a bug?

**Comment by UkcheolShin** [comment]
Thanks for reporting! I updated the directory name correctly.
