### ISSUE TITLE
About dataset structure

### ISSUE THREAD

**Issue by ghost** [UkcheolShin/ThermalMonoDepth#3]
The dataset structure you mentioned in README contains some files that are not available in ViViD++Rosbag. For example, **cali_ ther_ to_ rgb.yaml，avg_ velocity_ thermal.txt，poses_ thermal.txt**. How can I get these documents?

**Comment by UkcheolShin** [comment]
The current data structure is based on our pre-processed data of the vivid dataset (https://docs.google.com/forms/d/e/1FAIpQLSd2IndM_BvsBQ2NypmoF8hGNdVFLQcdHifbHFYAgl62K_z-Pw/viewform).
I plan to extend our work on the vivid++ dataset for depth and odometry evaluation, but currently, our source code doesn't support the vivid++ dataset.
